services:
  - type: web
    name: bot-hosting
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8270979575:AAGK9BnLpi-wfFTnvziUMl1vj89YRAFbIjg
      - key: ADMIN_IDS
        value: 8443743937
      - key: DATABASE_URL
        fromDatabase:
          name: bot-hosting-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: bot-hosting-redis
          property: connectionString
      - key: RENDER
        value: true
      - key: RENDER_EXTERNAL_URL
        value: https://bot-hosting.onrender.com

  - type: redis
    name: bot-hosting-redis
    plan: free
    maxmemoryPolicy: allkeys-lru

databases:
  - name: bot-hosting-db
    plan: free
    databaseName: hosting
    user: hosting_user
