services:
  - type: web
    name: bot hosting
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn render_bot:app
    envVars:
      - key: RENDER_EXTERNAL_HOSTNAME
        value: your-subdomain.onrender.com
